from typing import Protocol


class SamsungFrameClient(Protocol):
    async def connect(self): ...
    async def pair(self): ...
    async def close(self): ...
    async def get_device_info(self) -> dict: ...
    async def get_art_mode(self) -> str: ...
    async def get_current_artwork(self) -> dict: ...
    async def get_current_matte(self) -> str: ...
    async def get_available_mattes(self) -> dict: ...
    async def get_artwork_thumbnail(self, content_id: str) -> bytes: ...
    async def set_matte(self, content_id: str, matte: str): ...
    async def select_artwork(self, content_id: str): ...
    async def upload_artwork(self, data: bytes, matte: str) -> str: ...
